-- Tables to create: apikey, agentHost, agent, agentCapabilityGrant, approvalRequest
-- Columns to add: 
-- Generated by: better-auth compileMigrations()

create table "apikey" ("id" text not null primary key, "configId" text not null, "name" text, "start" text, "referenceId" text not null, "prefix" text, "key" text not null, "refillInterval" integer, "refillAmount" integer, "lastRefillAt" date, "enabled" integer, "rateLimitEnabled" integer, "rateLimitTimeWindow" integer, "rateLimitMax" integer, "requestCount" integer, "remaining" integer, "lastRequest" date, "expiresAt" date, "createdAt" date not null, "updatedAt" date not null, "permissions" text, "metadata" text);

create table "agentHost" ("id" text not null primary key, "name" text, "userId" text references "user" ("id") on delete cascade, "defaultCapabilities" text, "publicKey" text, "kid" text, "jwksUrl" text, "enrollmentTokenHash" text, "enrollmentTokenExpiresAt" date, "status" text not null, "activatedAt" date, "expiresAt" date, "lastUsedAt" date, "createdAt" date not null, "updatedAt" date not null);

create table "agent" ("id" text not null primary key, "name" text not null, "userId" text references "user" ("id") on delete cascade, "hostId" text not null references "agentHost" ("id") on delete cascade, "status" text not null, "mode" text not null, "publicKey" text not null, "kid" text, "jwksUrl" text, "lastUsedAt" date, "activatedAt" date, "expiresAt" date, "metadata" text, "createdAt" date not null, "updatedAt" date not null);

create table "agentCapabilityGrant" ("id" text not null primary key, "agentId" text not null references "agent" ("id") on delete cascade, "capability" text not null, "deniedBy" text references "user" ("id") on delete cascade, "grantedBy" text references "user" ("id") on delete cascade, "expiresAt" date, "createdAt" date not null, "updatedAt" date not null, "status" text not null, "reason" text, "constraints" text);

create table "approvalRequest" ("id" text not null primary key, "method" text not null, "agentId" text references "agent" ("id") on delete cascade, "hostId" text references "agentHost" ("id") on delete cascade, "userId" text references "user" ("id") on delete cascade, "capabilities" text, "status" text not null, "userCodeHash" text, "loginHint" text, "bindingMessage" text, "clientNotificationToken" text, "clientNotificationEndpoint" text, "deliveryMode" text, "interval" integer not null, "lastPolledAt" date, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);

create index "apikey_configId_idx" on "apikey" ("configId");

create index "apikey_referenceId_idx" on "apikey" ("referenceId");

create index "apikey_key_idx" on "apikey" ("key");

create index "agentHost_userId_idx" on "agentHost" ("userId");

create index "agentHost_kid_idx" on "agentHost" ("kid");

create index "agentHost_enrollmentTokenHash_idx" on "agentHost" ("enrollmentTokenHash");

create index "agentHost_status_idx" on "agentHost" ("status");

create index "agent_userId_idx" on "agent" ("userId");

create index "agent_hostId_idx" on "agent" ("hostId");

create index "agent_status_idx" on "agent" ("status");

create index "agent_kid_idx" on "agent" ("kid");

create index "agentCapabilityGrant_agentId_idx" on "agentCapabilityGrant" ("agentId");

create index "agentCapabilityGrant_capability_idx" on "agentCapabilityGrant" ("capability");

create index "agentCapabilityGrant_grantedBy_idx" on "agentCapabilityGrant" ("grantedBy");

create index "agentCapabilityGrant_status_idx" on "agentCapabilityGrant" ("status");

create index "approvalRequest_agentId_idx" on "approvalRequest" ("agentId");

create index "approvalRequest_hostId_idx" on "approvalRequest" ("hostId");

create index "approvalRequest_userId_idx" on "approvalRequest" ("userId");

create index "approvalRequest_status_idx" on "approvalRequest" ("status");
